### ISSUE TITLE
Can't use module in Azure Function App

### ISSUE THREAD

**Issue by DeV1L** [paulomarquesc/AzureRmStorageTable#1]
I try to import the module as described here http://stackoverflow.com/questions/37724769/how-to-install-a-powershell-module-in-an-azure-function

What i do:
1) Upload c:\Program Files\WindowsPowerShell\Modules\AzureRM.Storage\2.3.0\ into modules dir inside a function dir

2) Run from Kudu

```
PS D:\home\site\wwwroot\ExportTable2Table\modules> Import-Module AzureRmStorageTable.psd1
Import-Module : The specified module 'AzureRmStorageTable.psd1' was not loaded 
PS D:\home\site\wwwroot\ExportTable2Table\modules> because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module AzureRmStorageTable.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AzureRmStorageTable.psd1:S 
   tring) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm 
   ands.ImportModuleCommand
```

The file is exist
```
PS D:\home\site\wwwroot\ExportTable2Table\modules> ls AzureRmStorageTable.psd1


    Directory: D:\home\site\wwwroot\ExportTable2Table\modules


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
-a---         4/12/2017   2:06 PM      56000 AzureRmStorageTable.psd1         
```

**Comment by paulomarquesc** [comment]
Hi DeV1L,

Have you also installed the following pre-requisite modules?

AzureRM.Profile
AzureRM.Storage
AzureRM.Resources
Azure.Storage

I also released a new version of the module two weeks ago that will check for these modules using the #requires statement.

Please let me know.

Regards

Paulo

**Comment by paulomarquesc** [comment]
Hi DeV1L,

I just tested and it looks like you're missing the module name folder inside module folder like mine:

`D:\home\data\Functions\sampledata\modules\AzureRmStorageTable`

And inside this folder you should copy both the PSD1 and the PSM1 files as follows:

`PS D:\home\data\Functions\sampledata\modules\AzureRmStorageTable> dir


    Directory: D:\home\data\Functions\sampledata\modules\AzureRmStorageTable


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
-a---          5/8/2017   4:12 PM       1766 AzureRmStorageTable.psd1          
-a---          5/8/2017   4:12 PM      17528 AzureRmStorageTableCoreHelper.psm1


PS D:\home\data\Functions\sampledata\modules\AzureRmStorageTable>  `

After that I could load the AzureRMStorageTable without issues:

```
PS D:\home\data\Functions\sampledata> Import-module ./modules/AzureRmStorageTable/AzureRmStorageTable.psd1
PS D:\home\data\Functions\sampledata> get-command -module AzureRmStorageTable

CommandType     Name                                               ModuleName  
-----------     ----                                               ----------  
Function        Add-StorageTableRow                                AzureRmSt...
Function        Get-AzureStorageTableRowAll                        AzureRmSt...
Function        Get-AzureStorageTableRowByColumnName               AzureRmSt...
Function        Get-AzureStorageTableRowByCustomFilter             AzureRmSt...
Function        Get-AzureStorageTableRowByPartitionKey             AzureRmSt...
Function        Remove-AzureStorageTableRow                        AzureRmSt...
Function        Update-AzureStorageTableRow                        AzureRmSt...


PS D:\home\data\Functions\sampledata>  
```

Just be aware that you need to use AzureRmStorageTable version 1.0.0.8 or higher.

Regards

Paulo
