### ISSUE TITLE
Get-AzureStorageTable : Could not load file or assembly 'System.Spatial, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

### ISSUE THREAD

**Issue by sudeeptm** [paulomarquesc/AzureRmStorageTable#12]
Issued the following commands on Powershell console

$sa = Get-AzureRmStorageAccount -ResourceGroupName "myResourceGroup" -Name "myStorage"
$ctx = $sa.Context
$table = Get-AzureStorageTable -Table configuration -Context $ctx

Output:
Get-AzureStorageTable : Could not load file or assembly 'System.Spatial, Version=5.8.1.0, Culture=neutral,PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. HTTP StatusCode: 200 - HTTP Error Message: OK
At line:1 char:10
+ $table = Get-AzureStorageTable -Table configuration -Conte ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageTable], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTab
   leCommand

PS Version Output:
$psversiontable:

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Output of “get-module -name *azure* -listavailable”
[AzureModules.txt](https://github.com/paulomarquesc/AzureRmStorageTable/files/1557651/AzureModules.txt)

**Comment by paulomarquesc** [comment]
Hi sudeeptm,

In order to avoid issues with missing requirements or wrong DLL references I built a cmdlet (**Get-AzureStorageTableTable**) to specifically return the storage table reference, it is documented on https://blogs.technet.microsoft.com/paulomarques/2017/05/23/azure-rm-storage-tables-powershell-module-now-includes-support-for-cosmos-db-tables/.

Can you please replace the lines you pasted from your script with:

```powershell
$resourceGroup = "myResourceGroup"
$storageAccount = "mystorageaccount"
$tableName = "table01"
$table = Get-AzureStorageTableTable -resourceGroup $resourceGroup -tableName $tableName -storageAccountName $storageAccount
````

Regards

Paulo

**Comment by paulomarquesc** [comment]
Hi sudeeptm,

I could reproduce this issue in a brand new computer with Visual Studio 2017 15.5 installed with Azure SDK.

The AzureRm.Storage module located at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Storage which is installed by default with Visual Studio misses the System.Spatial DLL.

To resolve this issue in your machine, please install AzureRm.Storage from the PowerShell Gallery as follows:

```powershell
Install-Module AzureRm.Storage -AllowClobber -Force
```

Regards

Paulo
