### ISSUE TITLE
Question: is PowerShell Core supported?

### ISSUE THREAD

**Issue by eosfor** [paulomarquesc/AzureRmStorageTable#16]
Hi Paulo, is PowerShell Core supported?

**Comment by rossmeyer1** [comment]
@eosfor I'm working on supporting this now with most cmdlets working as expected, however I'm really struggling with getting Remove-AzureStorageTableRow working.

@paulomarquesc Are you able to help please?

**Comment by jakedenyer** [comment]
I was able to get this working in PowerShell Core. The biggest change between this Module and the one I refactored is that the .NET Core API's are asynchronous and do not have the synchronous methods exposed. You also have to use the Az Module instead of the Azure or AzureRm Module.

https://github.com/jakedenyer/AzStorageTable

I'm using this to test out a conversion of an existing module from PowerShell 5.1 to 6.1. I don't plan on supporting the repo above - I only published it to help out with PowerShell Core support for this module.

**Comment by rossmeyer1** [comment]
> I was able to get this working in PowerShell Core. The biggest change between this Module and the one I refactored is that the .NET Core API's are asynchronous and do not have the synchronous methods exposed. You also have to use the Az Module instead of the Azure or AzureRm Module.
> 
> https://github.com/jakedenyer/AzStorageTable
> 
> I'm using this to test out a conversion of an existing module from PowerShell 5.1 to 6.1. I don't plan on supporting the repo above - I only published it to help out with PowerShell Core support for this module.

I also found this to be the case and managed to convert all but the Remove-AzureStorageTableRow cmdlet. This would seem to be different to all of the others, so any help with that would be great.

**Comment by jakedenyer** [comment]
For the Remove-AzureStorageTableRow I changed

> $entityToDelete = invoke-expression "[Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity,$assemblySN]( `` `$table.CloudTable.Execute([Microsoft.WindowsAzure.Storage.Table.TableOperation,$assemblySN]::Retrieve(` `$partitionKey,  ` `$rowKey))).Result"

to

`$entityToDelete = invoke-expression "[Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity](`` `$table.CloudTable.ExecuteAsync([Microsoft.WindowsAzure.Storage.Table.TableOperation]::Retrieve(`` `$partitionKey,`` `$rowKey))).Result.Result"`

And

`$results += $table.CloudTable.Execute((invoke-expression "[Microsoft.WindowsAzure.Storage.Table.TableOperation,$assemblySN]::Delete(```$entityToDelete)"))`

to

`$results += $table.CloudTable.ExecuteAsync((invoke-expression "[Microsoft.WindowsAzure.Storage.Table.TableOperation]::Delete(`` `$entityToDelete)"))`

backticks are driving me crazy

**Comment by rossmeyer1** [comment]
> For the Remove-AzureStorageTableRow I changed
> 
> > $entityToDelete = invoke-expression "[Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity,$assemblySN]( `` `$table.CloudTable.Execute([Microsoft.WindowsAzure.Storage.Table.TableOperation,$assemblySN]::Retrieve(` `$partitionKey,  ` `$rowKey))).Result"
> 
> to
> 
> `` $entityToDelete = invoke-expression "[Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity](`` ``$table.CloudTable.ExecuteAsync([Microsoft.WindowsAzure.Storage.Table.TableOperation]::Retrieve(`` `$partitionKey, `` `$rowKey))).Result.Result"`
> 
> And
> 
> `` $results += $table.CloudTable.Execute((invoke-expression "[Microsoft.WindowsAzure.Storage.Table.TableOperation,$assemblySN]::Delete(```$entityToDelete)")) ``
> 
> to
> 
> `` $results += $table.CloudTable.ExecuteAsync((invoke-expression "[Microsoft.WindowsAzure.Storage.Table.TableOperation]::Delete(`` ``$entityToDelete)"))`
> 
> backticks are driving me crazy

Bravo! Well done.

**Comment by GHRoss** [comment]
@jakedenyer I'm getting the following when trying to import the module, any thoughts?

Import-Module : Assembly with same name is already loaded
At line:1 char:1
+ Import-Module /Users/Username/Az ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by paulomarquesc** [comment]
Hi Jake, thanks for the conversion, great work.
