### ISSUE TITLE
Customfilter with tabletimestamp

### ISSUE THREAD

**Issue by ikiris04** [paulomarquesc/AzureRmStorageTable#17]
Sorry for the simple question,

but how do you use customfilter with a date against the tabletimestamp column?

I've been trying to do the following:

et-AzureStorageTableRowByColumnName -table $storagetable -columnName "TableTimestamp" -value "datetime'2018-07-10T00:00:00Z'" -operator greaterthan

**Comment by KonTheCat** [comment]
I have the same exact question, please help!

**Comment by ZachMealing** [comment]
I also have this issue where when i run the above nothing is being returned?

**Comment by KonTheCat** [comment]
I read somewhere recently that we should just be creating our own timestamps and letting Azure manage that TableTimestamp. This is what I ended up doing in my case and it worked well enough. If you try to put a timestamp into a RowKey make sure you convert it into filetime or something like that or you will get errors, PartitionKey and RowKey seem to not accept spaces.

**Comment by ZachMealing** [comment]
@KonTheCat Thanks for the tip will see what i can come up with.
