### ISSUE TITLE
No way to use with SAS keys

### ISSUE THREAD

**Issue by brandoncasaba** [paulomarquesc/AzureRmStorageTable#2]
In order to use this API, you're required to get a table reference. You cannot get a table reference with a SAS token in the regular Azure API.

Example:
```
$ctx= New-AzureStorageContext -SasToken "?st=TIME&se=TIME&sp=r&sv=2015-04-05&tn=TABLENAME&sig=BASE64SIG" -StorageAccountName "AZURESTORAGEACCOUNT"
$table = Get-AzureStorageTable -Context $ctx "TABLENAME"

Get-AzureStorageTable : The remote server returned an error: (403) Forbidden. HTTP Status Code: 403 - HTTP Error Message: Forbidden
At line:1 char:10
+ $table = Get-AzureStorageTable -Context $ctx "TABLENAME"
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageTable], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand
```

This is because the Azure API will use the https://AZURESTORAGEACCOUNT.table.core.windows.net/Tables('TABLENAME')?sastoken URI path which will fail. Making a manual request with the  https://AZURESTORAGEACCOUNT.table.core.windows.net/TABLENAME?sastoken succeeds. 

Is there a way to get a table reference with a SAS token that works to utilize this module?

**Comment by paulomarquesc** [comment]
Hi Brandon,

I got back to the Product Group and they mentioned that it may be possible to work with Account SASs instead, the reference I got is the following document: [https://docs.microsoft.com/en-us/rest/api/storageservices/Constructing-an-Account-SAS?redirectedfrom=MSDN.
](url)

I started testing it but couldn't get working yet, if you can test and share how you created the Account SAS that would be great since I'm not going to be able to touch it for at least 3 weeks.

Regards

Paulo

**Comment by paulomarquesc** [comment]
I got this working, the trick is to get two contexts, the first, based on your own rights to the storage account, then build the SAS token using the cmdlet New-AzureStorageAccountSASToken (which requires a context created in the first place), then generate the second context based on the SAS token with your custom permissions: 

```
$resourceGroup = "pmcrg01"
$storageAccount = "pmcstorage01"
$tableName = "table01"
$saContext = (Get-AzureRmStorageAccount -ResourceGroupName $resourceGroup -Name $storageAccount).Context
$sas = New-AzureStorageAccountSASToken -Service Table -ResourceType Container,Object -Permission aul -StartTime "2017-06-17T00:00" -ExpiryTime "2017-06-18T00:00" -Protocol HttpsOnly -Context $saContext
$newContext = New-AzureStorageContext -SasToken $sas -StorageAccountName $storageAccount
$table = Get-AzureStorageTable -Context $newContext -Name $tableName`
```

Hope that this helps.

**Comment by brandoncasaba** [comment]
The problem with that is that requires a token that gives access to ALL tables... The example I gave is an application granting another party or application read only access to a specific table. If you're receiving a SAS token, it's presumable that you won't have full storage account access either through a SAS token granting such or the primary/secondary storage keys to the storage account.

It's doable using the normal C# APIs because you can get the table reference differently. This might be more an issue with the Azure-PowerShell project (https://github.com/Azure/azure-powershell) as it seems to be the Get-AzureStorageTable API that doesn't take in to account it may not have permissions to enumerate tables.

Utilizing the 8.1.4.0 .NET Azure Storage Library (from PowerShell):
```
>[appdomain]::currentdomain.getassemblies() | Where {$_ -match "Microsoft.WindowsAzure.Storage" }  | sort -property fullname | format-table fullname

FullName                                                                                                      
--------                                                                                                      
Microsoft.WindowsAzure.Storage, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35             
Microsoft.WindowsAzure.Storage, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35             
Microsoft.WindowsAzure.Storage, Version=8.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35             
Microsoft.WindowsAzure.Storage.DataMovement, Version=0.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

>$creds = new-object Microsoft.WindowsAzure.Storage.Auth.StorageCredentials "?sv=2016-05-31&tn=testTable&sig=BASE64SIG&spr=https&st=2017-06-17T07%3A00%3A00Z&se=2017-06-30T07%3A00%3A00Z&sp=r"

>$table = New-Object Microsoft.WindowsAzure.Storage.Table.CloudTable ("https://ACCOUNTNAME.table.core.windows.net/testTable", $creds)

>$tablequery = new-object Microsoft.WindowsAzure.Storage.Table.TableQuery

>$table.ExecuteQuery($tablequery)


Properties   : {[asdfasdgsdfg, Microsoft.WindowsAzure.Storage.Table.EntityProperty]}
PartitionKey : asdf
RowKey       : asdgfsdfg
Timestamp    : 6/1/2017 7:53:23 PM +00:00
ETag         : W/"datetime'2017-06-01T19%3A53%3A23.0938567Z'"
```

As of now, this is a usable workaround. 

Thanks,
Brandon
