### ISSUE TITLE
how to add DateTime Property using Add-StorageTableRow?

### ISSUE THREAD

**Issue by sudhirtibrewal** [paulomarquesc/AzureRmStorageTable#26]
how to add DateTime Property using Add-StorageTableRow?

**Comment by paulomarquesc** [comment]
Hi @sudhirtibrewal, this is an example:

Add-StorageTableRow -table $Table -partitionKey "datetest" -rowKey ([guid]::NewGuid().tostring()) -property @{"computerName"="COMP01";"lastUpdatedOn"=(get-date)}

The end result is a DateTime column in the table as follows:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/17993275/52178939-7ea51500-2791-11e9-9573-bf61cfe91826.png">

Please let me know if that works.

Regards

Paulo
