### ISSUE TITLE
AzureRmStorageTables cmdlets not supporting new az module

### ISSUE THREAD

**Issue by ShivaKodkandla** [paulomarquesc/AzureRmStorageTable#28]
recently we have migrated from azurerm to new az modules, after that commands from azurerm storage table module [Add-StorageTableRow, Get-AzureStorageTableRowAll, Get-AzureStorageTableRowByPartitionKey etc..]

also enabled AzureRmAliases but no luck, is there any workaround for this? if not we must introduce  azstoragetable module.

![image](https://user-images.githubusercontent.com/45571707/52632620-0dc7d080-2ee8-11e9-885e-cfaf190d9c03.png)

_____________
PS C:\Windows\system32> Get-Module az* -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name
---------- -------    ----
Script     1.2.1      Az.Accounts
Script     1.0.1      Az.Aks
Script     1.0.1      Az.AnalysisServices
Script     1.0.0      Az.ApiManagement
Script     1.0.0      Az.ApplicationInsights
Script     1.1.0      Az.Automation
Script     1.0.0      Az.Batch
Script     1.0.0      Az.Billing
Script     1.0.1      Az.Cdn
Script     1.0.0      Az.CognitiveServices
Script     1.2.0      Az.Compute
Script     1.0.0      Az.ContainerInstance
Script     1.0.1      Az.ContainerRegistry
Script     1.0.1      Az.DataFactory
Script     1.0.0      Az.DataLakeAnalytics
Script     1.0.2      Az.DataLakeStore
Script     1.0.0      Az.DevTestLabs
Script     1.0.0      Az.Dns
Script     1.1.0      Az.EventGrid
Script     1.0.0      Az.EventHub
Script     1.0.0      Az.HDInsight
Script     1.0.2      Az.IotHub
Script     1.0.1      Az.KeyVault
Script     1.1.0      Az.LogicApp
Script     1.0.0      Az.MachineLearning
Script     1.0.0      Az.MarketplaceOrdering
Script     1.0.0      Az.Media
Script     1.0.0      Az.Monitor
Script     1.1.0      Az.Network
Script     1.0.0      Az.NotificationHubs
Script     1.0.0      Az.OperationalInsights
Script     1.0.0      Az.PolicyInsights
Script     1.0.0      Az.PowerBIEmbedded
Script     0.7.0      Az.Profile
Script     1.0.1      Az.RecoveryServices
Script     1.0.0      Az.RedisCache
Script     1.0.0      Az.Relay
Script     1.1.1      Az.Resources
Script     1.0.0      Az.ServiceBus
Script     1.0.1      Az.ServiceFabric
Script     1.0.2      Az.SignalR
Script     1.1.0      Az.Sql
Script     1.0.2      Az.Storage
Script     1.0.0      Az.StreamAnalytics
Script     1.0.1      Az.TrafficManager
Script     1.1.0      Az.Websites
Manifest   1.0.0.23   AzureRmStorageTable

**Comment by paulomarquesc** [comment]
Hi ShivaKodkandla, I'm currently working on a new version of this module that will support some major changes coming up on Az.Storage module, amongst other changes it will support the new Az modules.

As a workaround for now, can you edit the file AzureRmStorageTableCoreHelper.psm1 and remove the line in the beginning of the file where we have the "#requires" and check if that will work?

Finally, please refer to https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-1.4.0#enable-azurerm-compatibility-aliases to enable compatibility with the old alises.

**Comment by paulomarquesc** [comment]
What can be als

**Comment by wuffers** [comment]
Tried the workaround above by removing the #requires line, but only some of the commands work. Didn't do a full test, but these were some of the errors on cmdlets:

`Get-AzureStorageTableRowAll : Method invocation failed because [Microsoft.WindowsAzure.Storage.Table.CloudTable] does not contain a method named 'ExecuteQuery'.
`
`Add-StorageTableRow : Method invocation failed because [Microsoft.WindowsAzure.Storage.Table.CloudTable] does not contain a method named 'Execute'.`

Only Az modules installed, no AzureRm modules. Enable-AzureRmAlias was on.

I'm now going to have to look at a side-by-side installation, as I only need some Az functionality on some scripts.

Any ETA on a AzureRmStorageTable that's compatible with Az without AzureRm?
