### ISSUE TITLE
Add support for batch operations

### ISSUE THREAD

**Issue by TarekSalha** [paulomarquesc/AzureRmStorageTable#31]
It would be very cool, if the usage of the batch API would be possible to speed operations up a lot. see https://docs.microsoft.com/en-us/dotnet/api/system.data.services.client.dataservicecontext.executebatch.

Currently I am having issues when e.g. deleting a lot of entities from a table (some millions) as a batch as they will be executed as single entity rest calls.

**Comment by paulomarquesc** [comment]
Thanks for the feedback @TarekSalha, I'll investigate this.

**Comment by ld0614** [comment]
I'm about to start using table storage to make 1000s (potentially 10,000-100,000) of calls at a time, anything that could be done to make this more efficient would be greatly appreciated 😄

**Comment by paulomarquesc** [comment]
Hi @TarekSalha, currently there is no such support in the SDK that would allow me to include batch deletion operations so I'm closing this item.

**Comment by davidschmalz** [comment]
Hello @paulomarquesc,

I was wondering whether this has now changed. Looking at the latest Azure SDK for .NET, there is now a [TableBatchOperation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablebatchoperation?view=azure-dotnet) Class that looks handy. Is this something that could be leveraged for this purpose? It would be very beneficial to be able to update 100's or 1000's of rows at once to limit runtime in our scripts.
