### ISSUE TITLE
Cannot find an overload for "ExecuteQuerySegmentedAsync" and the argument count: "2"

### ISSUE THREAD

**Issue by hari-narayanan94** [paulomarquesc/AzureRmStorageTable#33]
I am having an issue while trying to Query / Write Data to the Table ( Do note i have the latest version of all modules installed ) . 

Iam getting the below mentioned error : 
Cannot find an overload for "ExecuteQuerySegmentedAsync" and the argument count: "2".
At C:\Program Files\WindowsPowerShell\Modules\AzureRmStorageTable\2.0.1\AzureRmStorageTableCoreHelper.psm1:55 char:4
+             $Results = $Table.ExecuteQuerySegmentedAsync($TableQuery, ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

I am successfully able to get the Storage Context , Table Reference and also the Cloud Table property , but when i use Get-AzTableRow -Table $cloudtable i get the error mentioned above . 

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.2828                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.2828                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

Name                Version
----                -------
Az.Resources        1.2.1  
Az.Storage          1.1.0  
AzureRmStorageTable 2.0.1  

Exact Steps : 

$key = Get-AADAppoAuthToken -ClientID $appid -ClientSecret $pwd -TenantId $tenant #works
$token = "Bearer " + $key.access_token #works
$keyvaulturi = "https://harikeyvault.vault.azure.net/secrets/HariSecret?api-version=2016-10-01"
$keyvaultcontext = (Invoke-WebRequest -UseBasicParsing -Uri $keyvaulturi -Method GET -Headers @{Authorization=$token}).content
$storagekey = ($keyvaultcontext | ConvertFrom-Json).value #works
$storagecontext = New-AzStorageContext -StorageAccountName "haristorageaccount" -StorageAccountKey $storagekey #works
$tablecontext = Get-AzStorageTable -Name "haritable" -Context $storagecontext #works

$cloudtable = $tablecontext.CloudTable #works
$table = Get-AzTableRow -Table $cloudtable | Format-Table #not working

Please help

**Comment by hari-narayanan94** [comment]
Hi , I also just noticed that the Script is always working in Powershell and not working ( getting the same error ) when using Powershell ISE

**Comment by paulomarquesc** [comment]
Hi @hari-narayanan94 , can you please add here the complete output of **get-module \*az\* -ListAvailable**?

**Comment by hari-narayanan94** [comment]
Sorry for the Late response , we are trying to use the script in Azure Automation runbooks and we are still getting the same error . 


Name                                  Version
----                                  -------
Az.Accounts                           1.5.0  
Az.Aks                                1.0.1  
Az.AnalysisServices                   1.1.0  
Az.ApiManagement                      1.0.0  
Az.ApplicationInsights                1.0.0  
Az.Automation                         1.2.1  
Az.Batch                              1.0.0  
Az.Billing                            1.0.0  
Az.Cdn                                1.1.0  
Az.CognitiveServices                  1.0.1  
Az.Compute                            1.7.0  
Az.ContainerInstance                  1.0.1  
Az.ContainerRegistry                  1.0.1  
Az.DataFactory                        1.1.0  
Az.DataLakeAnalytics                  1.0.0  
Az.DataLakeStore                      1.1.0  
Az.DevTestLabs                        1.0.0  
Az.Dns                                1.0.0  
Az.EventGrid                          1.1.0  
Az.EventHub                           1.0.1  
Az.HDInsight                          1.0.0  
Az.IotHub                             1.0.2  
Az.KeyVault                           1.1.0  
Az.LogicApp                           1.2.1  
Az.MachineLearning                    1.0.0  
Az.MarketplaceOrdering                1.0.0  
Az.Media                              1.0.0  
Az.Monitor                            1.0.1  
Az.Network                            1.6.0  
Az.NotificationHubs                   1.0.0  
Az.OperationalInsights                1.1.0  
Az.PolicyInsights                     1.0.0  
Az.PowerBIEmbedded                    1.0.0  
Az.RecoveryServices                   1.2.0  
Az.RedisCache                         1.0.0  
Az.Relay                              1.0.0  
Az.Resources                          1.3.0  
Az.ServiceBus                         1.0.0  
Az.ServiceFabric                      1.0.1  
Az.SignalR                            1.0.2  
Az.Sql                                1.8.0  
Az.Storage                            1.2.0  
Az.StreamAnalytics                    1.0.0  
Az.TrafficManager                     1.0.1  
Az.Websites                           1.1.2  
AzTable                               2.0.2  
Azure.AnalysisServices                0.5.4  
Azure.Storage                         4.6.1  
AzureRM                               6.13.1 
AzureRM.AnalysisServices              0.6.14 
AzureRM.ApiManagement                 6.1.7  
AzureRM.ApplicationInsights           0.1.8  
AzureRM.Automation                    6.1.1  
AzureRM.Backup                        4.0.11 
AzureRM.Batch                         4.1.5  
AzureRM.Billing                       0.14.6 
AzureRM.Cdn                           5.0.6  
AzureRM.CognitiveServices             0.9.12 
AzureRM.Compute                       5.9.1  
AzureRM.Consumption                   0.3.7  
AzureRM.ContainerInstance             0.2.12 
AzureRM.ContainerRegistry             1.0.10 
AzureRM.DataFactories                 5.0.3  
AzureRM.DataFactoryV2                 0.5.11 
AzureRM.DataLakeAnalytics             5.1.4  
AzureRM.DataLakeStore                 6.2.1  
AzureRM.DevTestLabs                   4.0.9  
AzureRM.Dns                           5.1.0  
AzureRM.EventGrid                     0.3.7  
AzureRM.EventHub                      0.7.0  
AzureRM.HDInsight                     4.1.8  
AzureRM.Insights                      5.1.5  
AzureRM.IotHub                        3.1.8  
AzureRM.KeyVault                      5.2.1  
AzureRM.LogicApp                      4.1.4  
AzureRM.MachineLearning               0.18.5 
AzureRM.MachineLearningCompute        0.4.8  
AzureRM.MarketplaceOrdering           0.2.7  
AzureRM.Media                         0.10.4 
AzureRM.Network                       6.11.1 
AzureRM.NotificationHubs              5.0.3  
AzureRM.OperationalInsights           5.0.6  
AzureRM.PolicyInsights                1.1.0  
AzureRM.PowerBIEmbedded               4.1.10 
AzureRM.profile                       5.8.2  
AzureRM.RecoveryServices              4.1.9  
AzureRM.RecoveryServices.Backup       4.5.2  
AzureRM.RecoveryServices.SiteRecovery 0.2.12 
AzureRM.RedisCache                    5.1.0  
AzureRM.Relay                         0.3.12 
AzureRM.Resources                     6.7.3  
AzureRM.Scheduler                     0.16.10
AzureRM.ServiceBus                    0.6.13 
AzureRM.ServiceFabric                 0.3.15 
AzureRM.SignalR                       1.0.0  
AzureRM.Sql                           4.12.1 
AzureRM.Storage                       5.2.0  
AzureRM.StreamAnalytics               4.0.10 
AzureRM.Tags                          4.0.5  
AzureRM.TrafficManager                4.1.3  
AzureRM.UsageAggregates               4.0.5  
AzureRM.Websites                      5.2.0

**Comment by paulomarquesc** [comment]
Hi @hari-narayanan94, this is probably a conflict with AzureRM.Storage, in order to avoid conflicts, please remove all AzureRm modules.

**Comment by hari-narayanan94** [comment]
Hi , I have uninstalled all the AzureRM Modules by running Uninstall-AzureRm Command . Will contimue Testing and will revert back . thanks

**Comment by samarths-msft** [comment]
This repros for me as well. In my case, **get-module *az* -ListAvailable** does not show any AzureRM modules.
