### ISSUE TITLE
is usgov supported

### ISSUE THREAD

**Issue by chughesvf** [paulomarquesc/AzureRmStorageTable#38]
We just ran into a bug in our USGov deployment and realized it was stemming from the wrong url call to a storage table in USGov. Any clue if there is support for other DC types in this module?

**Comment by paulomarquesc** [comment]
Hi @chughesvf , yes, sovereign clouds are supported but not directly from Get-AzTableTable cmdlet. You need to use the following to get the table reference (note that in this case you need to create the table beforehand).

```powershell
$SaContext = (Get-AzStorageAccount -ResourceGroupName $resourceGroup -Name $storageAccount).Context
$table = (Get-AzStorageTable -Name $tableName -Context $saContext).CloudTable
```

**Comment by chughesvf** [comment]
can be closed as per above comment.
