### ISSUE TITLE
Make "Property" an optional parameter for Add-StorageTableRow

### ISSUE THREAD

**Issue by averhaegen** [paulomarquesc/AzureRmStorageTable#4]
Hi,

I was trying to use your module but I encountered an issue:
I have a storage table with only a PartitionKey and RowKey, but "**Add-StorageTableRow**" requires a "Property" value. So I cannot insert my rows.

Can you please make this an optional parameter?

Thanks!

**Comment by paulomarquesc** [comment]
Hi averhaegen,

I'll evaluate the impact and implement the change as soon as possible.

Regards

Paulo

**Comment by paulomarquesc** [comment]
Just did it, I'm not releasing the Powershell Gallery install yet but you can already download the files from here, next release on the gallery will have the support for Cosmos DB Table API GA.

**Comment by paulomarquesc** [comment]
Hi averhaegen, 

I just published version 1.0.0.21 on Powershell Gallery so this change is already there as well.

Regards

Paulo
