### ISSUE TITLE
Parameter storageaccount or table

### ISSUE THREAD

**Issue by WithHolm** [paulomarquesc/AzureRmStorageTable#44]
Hi,
is it possible to add support for using `[Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageTable]` or `[Microsoft.Azure.Commands.Management.Storage.Models.PSStorageAccount]` (get-azstorageaccount and get-azstoragetable)?

**Comment by paulomarquesc** [comment]
Hi WithHolm,

Not sure in what context you need to use this but you can use both cmdlets you listed to make it work as follows:

```powershell
C:\Users\pmarques> $StorageAccount = Get-AzStorageAccount -ResourceGroupName support-rg -Name pmcstorage08
C:\Users\pmarques> $table = (Get-AzStorageTable -Name table01 -Context $StorageAccount.Context).CloudTable
C:\Users\pmarques> Get-AzTableRow -Table $table -CustomFilter "RowKey eq '1448'"


value          : 1448-([guid]::NewGuid().tostring())
PartitionKey   : lotsOfRows
RowKey         : 1448
TableTimestamp : 4/10/2019 3:13:57 PM -07:00
Etag           : W/"datetime'2019-04-10T22%3A13%3A57.1658259Z'"
```

Regards

Paulo

**Comment by donghexu** [comment]
Reassign to akash, who is the current owner.

Sent from my iPhone

On Dec 10, 2019, at 7:58 AM, Paulo Marques <notifications@github.com> wrote:

﻿

Hi WithHolm,

Not sure in what context you need to use this but you can use both cmdlets you listed to make it work as follows:

C:\Users\pmarques> $StorageAccount = Get-AzStorageAccount -ResourceGroupName support-rg -Name pmcstorage08
C:\Users\pmarques> $table = (Get-AzStorageTable -Name table01 -Context $StorageAccount.Context).CloudTable
C:\Users\pmarques> Get-AzTableRow -Table $table -CustomFilter "RowKey eq '1448'"


value          : 1448-([guid]::NewGuid().tostring())
PartitionKey   : lotsOfRows
RowKey         : 1448
TableTimestamp : 4/10/2019 3:13:57 PM -07:00
Etag           : W/"datetime'2019-04-10T22%3A13%3A57.1658259Z'"

Regards

Paulo
