### ISSUE TITLE
Duplicate Record when using 'Update-AzTableRow' to edit the PartionKey

### ISSUE THREAD

**Issue by JulienFloris** [paulomarquesc/AzureRmStorageTable#51]
**Describe the bug**
When using 'Update-AzTableRow' and trying to edit the 'PartitionKey' it creates an duplicate Record and does not update the existing Row. 

**Error Message**
No Error Message 

**PowerShell Version**
With PS Version 5.1 and version 7

**Complete list of Azure related Powershell modules**
2.0.2      AzTable

**Code Snippet**
```PowerShell

# Get Existing Table that is empty
$Table = Get-AzStorageTable -Context $StorageAccount.Context -Name $TableName

# Add Record
Add-AzTableRow -Table $Table.CloudTable -PartitionKey 'true' -RowKey 1 -property @{
    Property1 = 'Value1'
    Property2 = 'Value2'
}

# Get Table Content
$Row = Get-AzTableRow -Table $Table.CloudTable -ColumnName RowKey -Value 1 -Operator Equal
$Row | Format-Table
<#
Property1 Property2 PartitionKey RowKey
--------- --------- ------------ ------
Value1    Value2    true         1     "
#>

# Update Record PartitionKey
$row.PartitionKey = 'False'
Update-AzTableRow -Table $Table.CloudTable -entity $Row

# Get Table Content
Get-AzTableRow -table $Table.CloudTable | Format-Table
<#
Property1 Property2 PartitionKey RowKey
--------- --------- ------------ ------
Value1    Value2    False        1     "
Value1    Value2    true         1     "
#>

```

**More information**
 - OS: Windows Server 2016

**Comment by paulomarquesc** [comment]
@PaulCheng and @sakash279 , can you double check this? I think this is a behavior that comes from the Table SDK.

**Comment by PaulCheng** [comment]
Partition key and row key cannot be updated, as they are used to identify an entity. To do so you will need to add and delete as 2 operations.
Update-AzTableRow invokes InsertOrMerge, which is why you got 2 entries. That'll be the known limitation in order to achieve convenience as opposed to exposing all storage APIs.

**Comment by JulienFloris** [comment]
Can the Powershell Module compensate if ParitionKey gets updated? Or should i compensate for this in my code?

**Comment by paulomarquesc** [comment]
Unfortunately not, the idea of this module is to be as much as possible a 1:1 match with the SDK so developers can easily transition from .net to Powershell and vice-versa, this change would mask this behavior.

**Comment by JulienFloris** [comment]
Understandable and not a problem.
Maybe an suggestion to make an note of this in the documentation for the next person. 
Your rapid response helps a lot in my development, **thank you for that!**
