### ISSUE TITLE
Apparent incompatibility with Az version 3.8.0

### ISSUE THREAD

**Issue by cronjevh** [paulomarquesc/AzureRmStorageTable#53]
**Describe the bug**
AzTable commands started failing after upgrading to Az v.3.8.0 release 4 days ago. After reverting to Az v.3.7.0, AzTable works as expected, but the following warning are visible in the log: 

     WARNING: Breaking changes in the cmdlet 'Get-AzStorageTable' :
      WARNING:  - "The output type 'Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageTable' is changing"
      WARNING: 	Change description : AzureStorageTable.CloudTable.ServiceClient will have 2 properties removed in a future release: ConnectionPolicy, ConsistencyLevel.

**Error Message**
ERROR: The 'Get-AzStorageTable' command was found in the module 'Az.Storage', but the module could not be loaded. For more information, run 'Import-Module Az.Storage'

**PowerShell Version**
Include here the full output of the following command line:
Powershell Core 6

**Code Snippet**
Paste here the code, from how you get the table reference up to the time you get the error

**More information**
 - OS: docker mcr.microsoft.com/dotnet/core/aspnet:2.2

**Additional context**
Using AzTable inside the Dockerhub image azure-functions/powershell:latest

**Comment by paulomarquesc** [comment]
hi guys, @PaulCheng, @sakash279 , can you please take a look?

**Comment by PaulCheng** [comment]
The warning is irrelevant; the breaking change has not yet been implemented in 3.8.0.
I'm not able to repro on Windows OS. With PSVersion 7.0.0 and Az module 3.8.0 (az.storage 1.14.0), 
Get-AzStorageTable, Get-AzTableTable and Get-AzTableRow all work fine.
I'm not familiar with the asp.net core docker image. Please make sure AZ PS is updated properly, since PS update depends on how the module was installed at the first place, via MSI or cmdlet.

**Comment by blueww** [comment]
What's Powershell core version?
For Az 3.8.0 and later, Az.Storage need Powershell core minimum version of 6.2.4.

If you run "Import-Module Az.Storage", you probably will see the message to remind you install Powershell core 6.2.4 and later.

**Comment by cronjevh** [comment]
Thanks for checking it out .. I didn't consider the Az.Storage ps core dependency, kind of obvious now in retrospect, I'm sure Microsoft will update their images in due course.
