### ISSUE TITLE
Get-AzTableTable Fails

### ISSUE THREAD

**Issue by gjhardie** [paulomarquesc/AzureRmStorageTable#54]
**Describe the bug**
Attempt to execute Get-AzTableTable as follows:
$resourceGroup = "WVD-USCENT-RG"
$tableName = "WVD-AI-Storage"
$storageAccount = "cosmos-wvd-sktuoy7"
$table = Get-AzTableTable -resourceGroup $resourceGroup -TableName $tableName -storageAccountName $storageAccount

**Error Message**
Exception: /Users/gj/.local/share/powershell/Modules/AzTable/2.0.3/AzureRmStorageTableCoreHelper.psm1:133:3
Line |
 133 |          throw "Invalid table name: $TableName"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid table name: WVD-AI-Storage
**PowerShell Version**
Include here the full output of the following command line:
```powershell
$PSVersionTable
```

**Complete list of Azure related Powershell modules**
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.9.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave…
Script     4.1.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, Ne…
Script     0.1.6                 Az.CosmosDB                         Core,Desk {Get-AzCosmosDBSqlContainer, Get-AzCosmosDBSqlContai…
Script     0.1.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Get-AzWvdApplication, …
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegratio…
Script     2.0.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, G…
Script     2.2.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-…
Manifest   2.0.3                 AzTable                             Desk      {Add-AzTableRow, Get-AzTableRow, Get-AzTableRowAll, …
Binary     2.0.2.76              AzureAD                             Desk      

**Code Snippet**
See Description.

**More information**
 - OS: macOS Catalina 10.15.5
- Visual Studio Code 1.46.1
- 

**Additional context**
On  further investigation, it doesn't appear to recognise the new "Azure Cosmos DB account" type...only the old "Storage account" type.

I can quite happily create the Table with cmdlet in Az.CosmosDB.

**Comment by PaulCheng** [comment]
Can you please try a table name without - or _, like WVDAIStorage

**Comment by PaulCheng** [comment]
Also, this module doesn't support CosmosDB table yet. Due to lack of resource, we don't have eta yet.

**Comment by gjhardie** [comment]
Good afternoon Paul,
The last update lead me to believe you were supporting CosmosDB tables.  Sorry to hear this is not the case.
I'm a little surprised on lack of resource...though one or more were MSFT?

The context in which I need my PowerShell code to run is in Azure Automation Account RunBook.
I had considered whether it would be possible to simply embedded c# in PowerShell to provide access to the .Net API, then though how one would be able to reference the SDK in Azure Automation alluded me.

Any pointers, most welcome.

Kindest Regards, Graham.
