### ISSUE TITLE
Forbidden Response using SAS Token on a Single Table with Get-AzStorageTable

### ISSUE THREAD

**Issue by gwalkey** [paulomarquesc/AzureRmStorageTable#65]
Using AzTable 2.04

Sas Token was created 3 different ways
1) Azure Portal - right Click on Table "Get SAS Token"
2) Powershell New-AzStorageTableSASToken
3) Azure Storage Explorer

All three SAS Tokens created on the Table ALONE fail
Using a SAS Token on the ENTIRE STORAGE ACCOUNT Always works

Code is:
Import-Module -Name Az.Storage
Import-Module -Name Az.Resources
Import-Module -Name AzTable

$AzStorageAccount = "storage_accountname"
$TableName = 'TableName'
$TableSasToken ="?st=2021-02-25T15%3A40%3A11Z&se=2022-01-01T04%3A59%3A00Z&sp=raud&sv=2018-03-28&tn=TableName&sig=mysig"
$StorageCtx = New-AzStorageContext -StorageAccountName $AzStorageAccount -SasToken $TableSasToken
**$Table = Get-AzStorageTable -Name $tableName -Context $StorageCtx**

throws
Forbidden

DEBUG: 1:04:10 PM - GetAzureStorageTableCommand end processing, Start 7 remote calls. Finish 7 remote calls. Elapsed time 1538702.92 ms. Client operation id: Azure-Storage-PowerShell-ee008953-9bf3-4536-9ad2-74a5b8742830.

DEBUG: AzureQoSEvent: CommandName - Get-AzStorageTable; IsSuccess - False; Duration - 00:00:01.8729751;; Exception - Microsoft.Azure.Cosmos.Table.StorageException: Forbidden
   at Microsoft.WindowsAzure.Commands.Storage.Model.Contract.StorageTableManagement.DoesTableExist(CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.<ListTablesByName>d__12.MoveNext()
   at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.WriteTablesWithStorageContext(IEnumerable`1 tableList)
   at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Request Information

RequestID:7b83f525-9002-0011-80a0-0b6c7f000000
RequestDate:Thu, 25 Feb 2021 18:04:08 GMT
StatusMessage:Forbidden
ErrorCode:
ErrorMessage:This request is not authorized to perform this operation.
RequestId:7b83f525-9002-0011-80a0-0b6c7f000000
Time:2021-02-25T18:04:08.4574077Z;
DEBUG: Finish sending metric.
DEBUG: 1:04:10 PM - GetAzureStorageTableCommand end processing.

hitting the URL in a browser works fine
using the same Table-level SAS Token against the REST API directly also works fine

**Comment by paulomarquesc** [comment]
hi @gwalkey , unfortunately, `Get-AzStorageTable` is a cmdlet that is not owned/supported by the AzTables module, this is an official cmdlet from `Az.Storage` module and I suggest you to open an issue [there](https://github.com/Azure/azure-powershell).

**Comment by gwalkey** [comment]
Hey thanks, will do
I assumed this was your CMDLet
Too bad another MS piece of code is broken

**Comment by paulomarquesc** [comment]
One last comment, after the SAS token issue is fixed please change your line:

```powershell
$Table = Get-AzStorageTable -Name $tableName -Context $StorageCtx
```

with 

```powerahell
$Table = (Get-AzStorageTable -Name $tableName -Context $StorageCtx).CloudTable
```

**Comment by gwalkey** [comment]
yep. know about the sub-collection

**Comment by gwalkey** [comment]
Paulo, whats the deal with the Table module NOT being supported by MS?
Just trying to sell more Cosmos?

**Comment by gwalkey** [comment]
https://github.com/Azure/azure-powershell/issues/14394

they still didnt use the Az module but referenced the Cosmos DLL directly
ho hum

**Comment by gwalkey** [comment]
Paulo, whats the deal with the Table module NOT being supported by MS?
Just trying to sell more Cosmos?

**Comment by paulomarquesc** [comment]
@gwalkey, just for the sake of other customers having the same issue, the answer for how to instantiate a table object was given by Wei Wei from Storage team [here](https://github.com/Azure/azure-powershell/issues/14394#issuecomment-793468373).

**Comment by paulomarquesc** [comment]
Update on documentation to account for the case where customer have a table sas token and how to obtain the CloudTable from it.

https://github.com/paulomarquesc/AzureRmStorageTable/blob/master/docs/README.md#troubleshooting
