### ISSUE TITLE
Unable to Query Azure Storage Table using latest Azure PowerShell

### ISSUE THREAD

**Issue by blueelvis** [paulomarquesc/AzureRmStorageTable#7]
Hi,

I am unable to run `ExecuteQuery` on the CloudTable object which is used in your module. I imported the module and still it did not work. I am getting the following error -

> [DBG]: PS C:\Users\Pranav>> $t.CloudTable.ExecuteQuery($query)
> Cannot find an overload for "ExecuteQuery" and the argument count: "1".
> At line:1 char:1
> + $t.CloudTable.ExecuteQuery($query)
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodException
>     + FullyQualifiedErrorId : MethodCountCouldNotFindBest
>  
> 

Exact same issue is detailed over here as well - https://stackoverflow.com/questions/46836512/how-get-a-row-in-azure-storage-tables-using-powershell

> [DBG]: PS C:\Users\Pranav>> Get-Module -Name *azure*
> 
> ModuleType Version    Name                                ExportedCommands                                                                                                                    
> ---------- -------    ----                                ----------------                                                                                                                    
> Manifest   4.0.0      Azure.Storage                       {Get-AzureStorageBlob, Get-AzureStorageBlobContent, Get-AzureStorageBlobCopyState, Get-AzureStorageContainer...}                    
> Script     0.2.3.8    AzureAutomationAuthoringToolkit     {Get-AutomationCertificate, Get-AutomationConnection, Get-AutomationVariable, Get-AzureAutomationAuthoringToolkitConfiguration...}  
> Manifest   4.0.0      AzureRM.Profile                     {Add-AzureRmAccount, Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault...}                                         
> Manifest   5.0.0      AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppCredential...}                       
> Manifest   4.0.1      AzureRM.Storage                     {Add-AzureRmStorageAccountNetworkRule, Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, Get-AzureRmStorageAccountNameAvai...
> 

Any idea what could be going wrong?

**Comment by paulomarquesc** [comment]
Hi blueelvis,

Is this error happening when you're use my module cmdlets or when you  are trying to use the .net classes directly?

As stated in the stackoverflow, I implemented some measures on version 1.0.0.20 to try avoiding conflicts between DLL versions, older versions of the Microsoft.WindowsAzure.Storage.dll will result in the issue you're seeing. The version of this DLL I know works well is 8.5.

Regards

Paulo

**Comment by blueelvis** [comment]
Greetings Paulo,

I have raised the issue with the Azure Powershell team and they have acknowledged it over here - https://github.com/Azure/azure-powershell/issues/5030#issuecomment-348379444

;)

-Pranav

**Comment by paulomarquesc** [comment]
Great to know Pranav, thanks.
